location = /_app_check {
    internal;
    proxy_pass http://127.0.0.1:3100;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_set_header X-Firebase-AppCheck $http_x_firebase_appcheck;
}

location /auth/v1/ {
    auth_request /_app_check;
    proxy_pass http://127.0.0.1:8000;
    include /etc/nginx/snippets/supabase-proxy.conf;
}

location /rest/v1/ {
    auth_request /_app_check;
    proxy_pass http://127.0.0.1:8000;
    include /etc/nginx/snippets/supabase-proxy.conf;
}

location /storage/v1/object/sign/ {
    proxy_pass http://127.0.0.1:8000;
    include /etc/nginx/snippets/supabase-proxy.conf;
}

location /storage/v1/ {
    auth_request /_app_check;
    proxy_pass http://127.0.0.1:8000;
    include /etc/nginx/snippets/supabase-proxy.conf;
}
